# Generated by Django 6.0.5 on 2026-05-29 09:35

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_tj', models.CharField(max_length=100, verbose_name='Ном (тҷ)')),
                ('name_ru', models.CharField(max_length=100, verbose_name='Имя (ру)')),
                ('slug', models.SlugField(unique=True)),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Иконка (Emoji ё Синф)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категорияҳо',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('phone', models.CharField(db_index=True, max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Рақами телефон бояд дар формати +992XXXXXXXXX бошад', regex='^\\+?992?\\d{9}$')], verbose_name='Рақами телефон')),
                ('name', models.CharField(blank=True, max_length=120, verbose_name='Ном')),
                ('is_verified', models.BooleanField(default=False, help_text='Оё муштарӣ тасдиқ шудааст?', verbose_name='Тасдиқшуда')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('last_order_at', models.DateTimeField(blank=True, null=True)),
                ('total_spent', models.DecimalField(decimal_places=2, default=0, help_text='Маблағи умумии хариди ҳамаи заказҳо', max_digits=12)),
                ('orders_count', models.PositiveIntegerField(default=0)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Муштарӣ',
                'verbose_name_plural': 'Муштариён',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Масалан: "Хона", "Кор"', max_length=50, verbose_name='Номи адрес')),
                ('village', models.CharField(max_length=100, verbose_name='Деҳа/Шаҳр')),
                ('street', models.CharField(blank=True, max_length=200, verbose_name='Кӯча')),
                ('house', models.CharField(blank=True, max_length=50, verbose_name='Хона/Ҳавлӣ')),
                ('landmark', models.TextField(blank=True, help_text='Назди мағозаи Аҳмад, пушти масҷид ва ғ.', verbose_name='Нишона')),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Адрес',
                'verbose_name_plural': 'Адресҳо',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Рақами заказ')),
                ('customer_name', models.CharField(max_length=120, verbose_name='Номи муштарӣ')),
                ('customer_phone', models.CharField(max_length=20, verbose_name='Телефони муштарӣ')),
                ('address_village', models.CharField(max_length=100, verbose_name='Деҳа/Шаҳр')),
                ('address_street', models.CharField(blank=True, max_length=200, verbose_name='Кӯча')),
                ('address_house', models.CharField(blank=True, max_length=50, verbose_name='Хона')),
                ('address_landmark', models.TextField(blank=True, verbose_name='Нишона/Ориентир')),
                ('address_lat', models.FloatField(blank=True, null=True, verbose_name='Аввалият (latitude)')),
                ('address_lng', models.FloatField(blank=True, null=True, verbose_name='Дарозӣ (longitude)')),
                ('status', models.CharField(choices=[('NEW', 'Нав (Омодасозӣ)'), ('ACCEPTED', 'Қабулшуда'), ('DELIVERING', 'Дар роҳ'), ('COMPLETED', 'Супорида шуд'), ('CANCELLED', 'Бекор шуд')], db_index=True, default='NEW', max_length=20, verbose_name='Ҳолати заказ')),
                ('payment_method', models.CharField(choices=[('CASH', 'Нақдӣ (Ба курьер)'), ('CARD', 'Корти Миллӣ (Алиф/Душанбе Сити)'), ('TERMINAL', 'Тавассути терминал')], default='CASH', max_length=20, verbose_name='Усули пардохт')),
                ('notes', models.TextField(blank=True, verbose_name='Эзоҳ/Таманниёт')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Суммаи маҳсулот')),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Нархи дастраскунӣ')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Умумӣ')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Санаи супориш')),
                ('accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='Қабул шуд')),
                ('delivering_at', models.DateTimeField(blank=True, null=True, verbose_name='Дар роҳ')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Анҷом ёфт')),
                ('assigned_worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Корманд')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Муштарӣ')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказҳо',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OTPCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(db_index=True, max_length=20)),
                ('code', models.CharField(max_length=6)),
                ('is_used', models.BooleanField(default=False)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['phone', '-created_at'], name='api_otpcode_phone_aedaf1_idx')],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_tj', models.CharField(max_length=255, verbose_name='Номи маҳсулот (тҷ)')),
                ('name_ru', models.CharField(max_length=255, verbose_name='Имя товара (ру)')),
                ('slug', models.SlugField(unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Нарх')),
                ('sku', models.CharField(max_length=50, unique=True, verbose_name='Артикул')),
                ('stock', models.IntegerField(default=0, verbose_name='Маҷмӯъ')),
                ('low_stock_threshold', models.IntegerField(default=5, verbose_name='Ҳадди ақалли захира')),
                ('unit', models.CharField(default='шт', max_length=20, verbose_name='Воҳиди ченкунӣ')),
                ('image_url', models.URLField(blank=True, max_length=500, verbose_name='Ссылкаи расм')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='api.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Маҳсулот',
                'verbose_name_plural': 'Маҳсулотҳо',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255, verbose_name='Номи маҳсулот дар вақти заказ')),
                ('price_at_order', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Нарх дар вақти заказ')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Миқдор')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.order', verbose_name='Заказ')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='api.product', verbose_name='Маҳсулот')),
            ],
            options={
                'verbose_name': 'Қисми заказ',
                'verbose_name_plural': 'Қисмҳои заказ',
            },
        ),
    ]
