# Generated by Django 6.0.5 on 2026-05-29 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='cost_price_at_order',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Нархи харид дар вақти заказ'),
        ),
        migrations.AddField(
            model_name='product',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Нархи харид (Себестоимость)'),
        ),
    ]
