# Generated by Django 6.0.5 on 2026-05-30 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_product_image_url_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description_ru',
            field=models.TextField(blank=True, verbose_name='Описание (ру)'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_tj',
            field=models.TextField(blank=True, verbose_name='Тавсиф (тҷ)'),
        ),
    ]
