# Generated by Django 6.0.5 on 2026-06-04 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_product_description_ru_product_description_tj'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at'], 'verbose_name': 'Маҳсулот', 'verbose_name_plural': 'Маҳсулотҳо'},
        ),
    ]
