# Generated by Django 6.0.5 on 2026-06-17 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_product_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='accepted_via',
            field=models.CharField(blank=True, choices=[('site', 'Сайт'), ('telegram', 'Telegram')], default='site', max_length=10, verbose_name='Қабул шуд тавассути'),
        ),
    ]
